### PR TITLE
CommandCard action buttons are aligned now

### LINKED ISSUE #88: Command card action alignment ( UI / MUI )
**Describe the bug**
Command cards do not have the same size which causes card actions ( buttons ) in a row not to be aligned with other card actions

**To Reproduce**
1. Go to the main page
2. Click on sidebar
3. Click on commands

**Expected behavior**
Card actions should align themselves to the end of the command card component

**Screenshots**
Current UI :
Screenshot 2024-05-14 031823

Excepted UI :
Screenshot 2024-05-14 040608

[ x ] I will fix this issue and create a PR

### PR DESCRIPTION
**Pull request by Sky-De**
### Fix for issue #88
By adding some lines of styles and class names to the command card component this issue is fixed

### Screenshot
chrome-capture-2024-4-14 (2)

### Consideration
whenever you change the data of these cards ( probably with longer descriptions ) tag me to take another look at the overall behavior of command card components, with this PR I have tried to fix the issue with a minimum amount of code change
if you have any questions feel free to ask, otherwise let me know about your satisfaction of changes by merging this PR, thanks, skyDe

### CODE REVIEW

**Comment by gbowne1** [comment]
@Sky-De reviewed your PR, but it needs to have a prettier run on the code so that the CI works.

do a `npm run lint:fix && npm run prettier:fix` and then recommit to the PR branch.

Oh and should be no need to force push.

Let me know. Thanks!

**Comment by Sky-De** [comment]
> @Sky-De reviewed your PR, but it needs to have a prettier run on the code so that the CI works.
> 
> do a `npm run lint:fix && npm run prettier:fix` and then recommit to the PR branch.
> 
> Oh and should be no need to force push.
> 
> Let me know. Thanks!

@gbowne1 I did run: `npm run lint: fix && npm run prettier: fix`, and I rewrote this commit history with a new one, I hope it is fixed now, check it, thanks

**Comment by gbowne1** [comment]
Yes @Sky-De that appears to have fixed the CI issue.  Thanks. 

I should mention that because this project repo has a lot of working code, altough incomplete, I have implemented policy that it will require 2 approving reviews for merge in order to have any PR merged and the CI test must pass, so will wait for @jarmentor to review.

After a person has 5 successful PR merges they will be invited to be a collaborator.  You have 4 successful merges also. Once this gets a merge I will invite you.

Thanks

**Review by gbowne1 — APPROVED** [review]
- [x] checked out this change locally for testing and review for merge 

This appears to have fixed the CSS issues with the UI.

The code looks good. The CI tests will pass.

Approving this PR for merge.

**Review by jarmentor — APPROVED** [review]
- [X] checked out this change locally for testing and review for merge

This fixes an issue where action buttons were not aligned to the end of the CommandCard component.

CI Passes 🎉 

Thank you for your contributions @Sky-De 

Approving this PR for merge and merging.

**Pull request merged**
