### PR TITLE
Add Close Button to DrawerMenu Component

### LINKED ISSUE #33: [TODO][Bug] There is no UI item to close the drawer
There is no close button to close the drawer 

Maybe add an X or a close button or some other element to close the drawer

### PR DESCRIPTION
**Pull request by Babuprasanth27**
Implemented a close button using IconButton and CloseIcon from Material-UI.
Added functionality to close the drawer when the close button is clicked.
Ensured compatibility with Windows by incorporating the cross-env package.

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
-  [x] checked out this change locally for testing and review for merge 
- [x] manually reviewed code for errors etc

This PR adds code that closes the drawer with an X close icon.  It appears to work properly. 

Approving this PR for merge.

Thanks for the opportunity to review your PR and for your contribution @Babuprasanth27

**Review by jarmentor — CHANGES_REQUESTED** [review]
- [X] checked out this change locally for testing and review for merge
- [X] manually reviewed code for errors etc

This PR adds a close icon to the DrawerMenu and seems work as expected.

This is a minor thing, but our prettier checks are failing due to the single quotes in DrawerMenu.js:19

@Babuprasanth27 thanks for your work on this issue! Can you please revise line 19 of DrawerMenu.js to use ~single~ *double* quotes so that [our checks](https://github.com/gbowne1/TwitchBot/pull/93/checks) pass 😅

**Comment by Babuprasanth27** [comment]
@jarmentor Thanks for reviewing my PR. Shall I modify the single quotes to double quotes and make another PR?

**Comment by gbowne1** [comment]
Just recommit the double quote fixes to your PR branch @Babuprasanth27

**Comment by Babuprasanth27** [comment]
@gbowne1 @jarmentor I have recommit with the double quotes. Please review it.

**Comment by jarmentor** [comment]
@Babuprasanth27 thanks! did you push your changes to the remote? I only see the [one commit](https://github.com/gbowne1/TwitchBot/pull/93/commits)

**Comment by Babuprasanth27** [comment]
@jarmentor Sorry, I have made another PR. Now you can see the change in this PR. The new Commit has been added. By adding double quotes I think the code needs Indent, if it does not work, please ping me I will recommit again, or if it works, then no worries. Please review it.

**Comment by Babuprasanth27** [comment]
@jarmentor  Review now I hope it works now.
As I am new to open-source contributions, there might be some initial challenges, but I am a fast learner and will rectify any mistakes promptly. Thank you for your patience and guidance in solving these issues. I look forward to continuing my contributions. Please feel free to assign any further issues to me.

**Comment by gbowne1** [comment]
@jarmentor @Babuprasanth27 not sure what to do here. Now there's two PRs basically the same.

**Comment by Babuprasanth27** [comment]
@gbowne1 @jarmentor Go ahead with this PR.

**Review by gbowne1 — APPROVED** [review]
Approving final changes to this PR.  Workflow should now pass.

**Review by jarmentor — APPROVED** [review]
Approving these changes for merge and merging. Workflows pass. Thanks for your contributions @Babuprasanth27!

**Comment by Babuprasanth27** [comment]
@gbowne1 @jarmentor Thanks for your guidance and patience. This is my first open-source contribution which I completed and you merged into the main repo. I am super excited to make more contributions.

**Pull request merged**
