### PR TITLE
tests added for About.js and AppBar.js

### LINKED ISSUE #24: [TODO] Add Jest/React Testing Library tests
A good app needs some tests. The one we have is the default for Jest/RTL that comes with Create React App 5.

Add a test folder and create some initial tests for the UI,etc.

### PR DESCRIPTION
**Pull request by Sky-De**
### This is a starting point to fix the issue #24

Screenshot 2024-02-14 140133

### CODE REVIEW

**Comment by gbowne1** [comment]
@Sky-De 

Thanks for the PR.  This is great but this has the old App.js.. The App.js got updated today in a earlier PR.  Fix the conflicts with App.js and recommit.

**Comment by Sky-De** [comment]
> @Sky-De
> 
> Thanks for the PR. This is great but this has the old App.js.. The App.js got updated today in a earlier PR. Fix the conflicts with App.js and recommit.

@gbowne1 it is done by second commit

**Review by gbowne1 — APPROVED** [review]
- [x] checked out this change for review and testing for merge 

This change adds the initial tests for the TwitchBot.

They appear to work just as expected.

Approving for merge and merging 

Thanks for the opportunity to review your PR and for your contributions @Sky-De

**Comment by Sky-De** [comment]
@gbowne1Hi, if you are satisfied with the pre-tests, I can test other components as well. inform me please, thanks

**Comment by gbowne1** [comment]
@Sky-De 

Please feel free to continue making tests.  The ones you made work pretty well so far.

**Pull request merged**
