### PR TITLE
Add Dark Mode Toggle

### LINKED ISSUE #8: [TODO] Add Dark Mode / Light Mode theme switch and ThemeContext
- Add ThemeContext.js
- modify AppBarComponent.js
- modify App.js with CssBaseLine, ThemeContext, ThemeProvider

### PR DESCRIPTION
**Pull request by jarmentor**
- Adds user-preference aware dark mode to the application via a ThemeProvider.
- Adds a toggle in the AppBar to switch the theme context.
- Minor formatting adjustments.

### CODE REVIEW

**Comment by jarmentor** [comment]
@gbowne1 opening a pull request for issue #8

**Comment by gbowne1** [comment]
@jarmentor 

I have reviewed and merged a couple of your PRs, sync and please fix the newq merge conflicts with this PR

I will finish review and test and merge once

**Comment by jarmentor** [comment]
Greetings @gbowne1, I've resolved the merge conflicts - thank you for your review.

**Review by gbowne1 — COMMENTED** [review]
- [x] checked out this change PR for testing and review for merge 

This change adds dark mode light mode toggle, theme support, etc. 

It appears to work as described by the new change.

Approving this PR for merge and merging 

Thanks for the opportunity to review your PR and for your contributions @jarmentor

**Pull request merged**
