### PR TITLE
tests is done for CommandList component

### PR DESCRIPTION
**Pull request by Sky-De**
### we had "testing" before and this is "testing1"

Screenshot 2024-02-19 165733

### CODE REVIEW

**Comment by gbowne1** [comment]
@Sky-De 

This has a conflict with CommandList.js

Please fix this and recommit.  Thanks

**Comment by Sky-De** [comment]
> @Sky-De
> 
> This has a conflict with CommandList.js
> 
> Please fix this and recommit. Thanks

#### sure, but let me know if it is ok with you I remove the commands array from the CommandList component and add above that : 

Screenshot 2024-02-20 021608

#### then I can import commands array to test and as a result even if you change command array elements it will not broke test and it would be more dynamic  :

Screenshot 2024-02-20 021719

**Comment by gbowne1** [comment]
@Sky-De 

That would be fine. There may be more commands to add so being able to add commands to the list will help that wont break the tests

**Comment by Sky-De** [comment]
@gbowne1 The second commit has been completed and the conflict has been resolved

**Review by gbowne1 — APPROVED** [review]
-[x] checked out this change for testing and review for merge 

This change adds tests for the commands 

These appears to work as expected 

Approving this PR for merge and merging 

@Sky-De thanks for the opportunity to review your PR and for your contributions to this project

**Comment by Sky-De** [comment]
> -[x] checked out this change for testing and review for merge
> 
> This change adds tests for the commands
> 
> These appears to work as expected
> 
> Approving this PR for merge and merging
> 
> @Sky-De thanks for the opportunity to review your PR and for your contributions to this project

@gbowne1 You're welcome, and it's my pleasure to assist you. After going through your bio, I must say that I admire you. You are an exceptional individual.

**Comment by gbowne1** [comment]
thanks @Sky-De

**Comment by gbowne1** [comment]
@Sky-De if you feel inclined to do so, this project I have needs tons of work, including tests..

https://github.com/gbowne1/reactsocialnetwork/issues/

The 3 or 4 people working on it havent done much in ~1yr.

Tests are Jest, RTL, cypress..

**Pull request merged**
