### PR TITLE
tests done for Help.js

### PR DESCRIPTION
**Pull request by Sky-De**
Screenshot 2024-02-22 050827

### Also i used helpContent obj in Help.js

Screenshot 2024-02-22 050901

### CODE REVIEW

**Comment by jarmentor** [comment]
Greetings -- just want to note that not all tests pass. The ones that are relevant to the PR do.

(unsure if this is the place to note this; I'm happy to raise issue)

Screenshot 2024-02-22 at 2 14 08 PM

**Comment by Sky-De** [comment]
@jarmentor i see, i had some difficulty to update main branch because my operation system, then i just copied those tests, i will fix it right now, thanks for informing me

**Comment by Sky-De** [comment]
> Greetings -- just want to note that not all tests pass. The ones that are relevant to the PR do.
> 
> (unsure if this is the place to note this; I'm happy to raise issue)
> 
> Screenshot 2024-02-22 at 2 14 08 PM

@jarmentor  Yes, I understand. The best thing about testing is that it helps to identify any issues or changes that may cause test failures. I ran a test on the About.js file and it seems that there have been some changes that caused the test to fail. Therefore, I will rewrite About.test.js to test the updated version of About.js and push new commit , review and test it, thanks for informing

**Comment by Sky-De** [comment]
@jarmentor it is done 

Screenshot 2024-02-22 150025

**Review by gbowne1 — APPROVED** [review]
- [x] Checked out this change locally for testing and review for merge

This change adds and fixes tests and updates components for testing.

They now appear to work fine,  but the components/pages are not in their final state so the tests willl need to be updated.  Aside from this.

Approving for merge

**Review by jarmentor — APPROVED** [review]
- [X]  Checked out this change locally for testing and review for merge

These changes adjust the tests. Though @gbowne1 is right, since things aren't in their final state tests will need gradual adjustment as we develop.

Approved for merged & merging.

@Sky-De thank you for your test fixes and the opportunity to review your PR.

**Pull request merged**
