### PR TITLE
fix log in bug

### PR DESCRIPTION
**Pull request by Amrani-Farouk-Hossam-Eddine**

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
- [x] checked out this change locally for testing and review for merge 

This change fixes the login.  It will need some tests to ensure the login and logout  behaves properly.

Other than that, this change works but hasnt been tested with any of the nodejs etc testing libraries yer so have added a request for login tests to be written with mocha, chai, jest, React testing library etc.. and maybe even use Morgan and Winston to do logging so its generating readable logs.

Approving this PR for merge

**Review by ghost — APPROVED** [review]
This PR addresses the login bug.

server.js works as expected with the current functionality

Approved to merge

**Review by jarmentor — APPROVED** [review]
* if only I were to approve from the correct account. Apologies.

**Comment by gbowne1** [comment]
@Amrani-Farouk-Hossam-Eddine please make sure that in the future your PRs include at least a basic description of your contributions and changes as described by the included CONTRIBUTING.md file. Other than that all good here thanks for your contributions :-)

**Pull request merged**
