### PR TITLE
Add close button drawermenu and Added Double Quotes

### PR DESCRIPTION
**Pull request by Babuprasanth27**
Added Double Quotes to DrawerMenu

### CODE REVIEW

**Comment by Babuprasanth27** [comment]
@jarmentor @gbowne1 Sorry, I have made another PR. So please review it.

**Comment by jarmentor** [comment]
just noting that this PR is related to #93 

- [X] checked out this change locally for testing and review for merge
- [X] manually reviewed code for errors etc

This is functionally good to merge, the only issue to resolve is some code styling things with prettier. 

@Babuprasanth27 - no worries! Thanks for your PR. If you could run `npm run preflight:fix` on your code and recommit the changes to the branch, that should resolve the check issues.

Despite the double quote fix (and thank you for that) , it looks like it's fussing about it being on one line.

Screenshot 2024-06-24 at 8 59 50 AM
Screenshot 2024-06-24 at 8 58 04 AM

**Comment by Babuprasanth27** [comment]
@jarmentor Please review the recent code I have committed.

**Comment by gbowne1** [comment]
@jarmentor @Babuprasanth27 not sure what to do here. Now that there's basically two PRs with the same.  

Yee its important to run the npm run preflight:fix before you commit and push to your PR branch.  If its not already it should be in our contribution documentation.

**Comment by gbowne1** [comment]
Closing this PR as a duplicate of #93

**Pull request closed without merging**
