### PR TITLE
Settings page UI DONE

### LINKED ISSUE #89: Setting page UI enhancement and responsiveness ( UI / MUI )
**Describe the bug**
Currently settings page is not aligned with material design principles

**To Reproduce**
1. Go to the main page
2. Click on sidebar
3. Click on the setting

**Expected behavior**
The UI of this page should be clean and ordered for better UI / UX, also it should be responsive

**Screenshots**
Current UI Desktop :
chrome-capture-2024-4-14

Current UI Mobile :
chrome-capture-2024-4-14 (1)

[ x ] I will fix this issue and create a PR

### PR DESCRIPTION
**Pull request by Sky-De**
### Fixes issue #89
now the settings page has a better UI which is responsive also, take a look at the result 

### Result

https://github.com/gbowne1/TwitchBot/assets/79264045/7645c5e3-90a6-4533-886f-1baf2cb00f2f

**If you have any questions feel free to ask**, otherwise let me know your satisfaction with the changes by merging this PR, thanks

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
This appears to have fixed issue with the UI for the settings page.

The code looks good.

Doesnt seem to cause any additional warnings or errors in the browser console.

I tested in Chrome and Firefox.

Approving this for merge.

**Comment by gbowne1** [comment]
The "Theme" light/dark switch in the Settings page can be removed as it is in the top navbar already.

**Comment by gbowne1** [comment]
I was trying to figure out what should be included in the bot settings page.

**Review by jarmentor — APPROVED** [review]
- [X] I've checked this out locally for testing and review

This change fixes #89 by enhancing the settings interface with responsive controls.

Code looks good

*Approving for merge

**Comment by gbowne1** [comment]
I like how it looks with different devices now (tested with Chrome and Firefox)  I assume streamers will want to have a tablet, phone or laptop running the client while they stream.

**Comment by Sky-De** [comment]
@gbowne1 @jarmentor Hi, may I ask you a favor? I'd appreciate it if you could take a look at my [Portfolio ](https://skyde-portfolio.netlify.app/)  and other projects. Please let me know what you think about them, and if you like them, please give them a **STAR.** All public projects can be found in the PROJECTS section of my portfolio. Within that section, you can find live demo links as well as repository links related to each project.And if you like my project please mention other colleagues of these projects here to check my [Portfolio ](https://skyde-portfolio.netlify.app/), thanks thanks

**Pull request merged**
